name: rtd
channels:
  - numba/label/dev
dependencies:
  - python
  # pip for installing llvmlite itself
  - pip
  - llvmdev=15
  - cmake
  - make
  - docutils==0.16
  - gcc_linux-64=11
  - gxx_linux-64=11
  - sphinx_rtd_theme

